### ISSUE TITLE
TechReborn ores not generating in the beneath

### ISSUE THREAD

**Issue by megaloloful** [Shinoow/The-Beneath#1]
I've already reported it to the TechReborn authors and they said the bug is on your side. Something about returning  false on isSurfaceWorld.

**Comment by Shinoow** [comment]
That sounds rather like intended behavior on their end, as their code is meant to only generate the ores in the Overworld (which the isSurfaceWorld flag exists for, checking whether or not the world is the "regular" world, or a different dimension). Since The Beneath isn't the Overworld, it won't return true on that, meaning the TechReborn ore generation won't do anything in there, as that dimension isn't the Overworld.
